apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: trungs-secret
  namespace: kubernetes-external-secrets
secretDescriptor:
  backendType: secretsManager
  data:
    - key: hello-service/credentials1
      name: password
      property: password
    - key: hello-service/credentials1
      name: username
      property: username
